name: Demo Workflow

on:
  workflow_dispatch:

jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"

  step2:
    needs: step1
    runs-on: ubuntu-latest
    steps:
      - run: echo "World"
